title: "Preprint Picnic 🔥"
email: "hello@paper-picnic.com"
author: "Moritz Marbach"
description: "A weekly basket with the latest preprints in political science."
baseurl: ""
url: "https://preprint.paper-picnic.com/"
github_username: "sumtxt"
exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - credentials.R